import '../../models/language_option.dart';

/// Curated list of 140 languages with native-script labels.
/// Ordered loosely by global speaker count so defaults feel sensible.
class SupportedLanguages {
  const SupportedLanguages._();

  static const List<LanguageOption> all = [
    LanguageOption(code: 'en', englishName: 'English', nativeName: 'English'),
    LanguageOption(code: 'zh', englishName: 'Mandarin Chinese', nativeName: '中文'),
    LanguageOption(code: 'hi', englishName: 'Hindi', nativeName: 'हिन्दी'),
    LanguageOption(code: 'es', englishName: 'Spanish', nativeName: 'Español'),
    LanguageOption(code: 'ar', englishName: 'Arabic', nativeName: 'العربية'),
    LanguageOption(code: 'bn', englishName: 'Bengali', nativeName: 'বাংলা'),
    LanguageOption(code: 'pt', englishName: 'Portuguese', nativeName: 'Português'),
    LanguageOption(code: 'ru', englishName: 'Russian', nativeName: 'Русский'),
    LanguageOption(code: 'ja', englishName: 'Japanese', nativeName: '日本語'),
    LanguageOption(code: 'pa', englishName: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ'),
    LanguageOption(code: 'de', englishName: 'German', nativeName: 'Deutsch'),
    LanguageOption(code: 'jv', englishName: 'Javanese', nativeName: 'Basa Jawa'),
    LanguageOption(code: 'ko', englishName: 'Korean', nativeName: '한국어'),
    LanguageOption(code: 'fr', englishName: 'French', nativeName: 'Français'),
    LanguageOption(code: 'te', englishName: 'Telugu', nativeName: 'తెలుగు'),
    LanguageOption(code: 'mr', englishName: 'Marathi', nativeName: 'मराठी'),
    LanguageOption(code: 'tr', englishName: 'Turkish', nativeName: 'Türkçe'),
    LanguageOption(code: 'ta', englishName: 'Tamil', nativeName: 'தமிழ்'),
    LanguageOption(code: 'vi', englishName: 'Vietnamese', nativeName: 'Tiếng Việt'),
    LanguageOption(code: 'ur', englishName: 'Urdu', nativeName: 'اردو'),
    LanguageOption(code: 'it', englishName: 'Italian', nativeName: 'Italiano'),
    LanguageOption(code: 'gu', englishName: 'Gujarati', nativeName: 'ગુજરાતી'),
    LanguageOption(code: 'pl', englishName: 'Polish', nativeName: 'Polski'),
    LanguageOption(code: 'uk', englishName: 'Ukrainian', nativeName: 'Українська'),
    LanguageOption(code: 'fa', englishName: 'Persian', nativeName: 'فارسی'),
    LanguageOption(code: 'ml', englishName: 'Malayalam', nativeName: 'മലയാളം'),
    LanguageOption(code: 'kn', englishName: 'Kannada', nativeName: 'ಕನ್ನಡ'),
    LanguageOption(code: 'or', englishName: 'Odia', nativeName: 'ଓଡ଼ିଆ'),
    LanguageOption(code: 'my', englishName: 'Burmese', nativeName: 'မြန်မာ'),
    LanguageOption(code: 'th', englishName: 'Thai', nativeName: 'ไทย'),
    LanguageOption(code: 'nl', englishName: 'Dutch', nativeName: 'Nederlands'),
    LanguageOption(code: 'ps', englishName: 'Pashto', nativeName: 'پښتو'),
    LanguageOption(code: 'ro', englishName: 'Romanian', nativeName: 'Română'),
    LanguageOption(code: 'sw', englishName: 'Swahili', nativeName: 'Kiswahili'),
    LanguageOption(code: 'am', englishName: 'Amharic', nativeName: 'አማርኛ'),
    LanguageOption(code: 'ha', englishName: 'Hausa', nativeName: 'Hausa'),
    LanguageOption(code: 'yo', englishName: 'Yoruba', nativeName: 'Yorùbá'),
    LanguageOption(code: 'ig', englishName: 'Igbo', nativeName: 'Igbo'),
    LanguageOption(code: 'zu', englishName: 'Zulu', nativeName: 'isiZulu'),
    LanguageOption(code: 'xh', englishName: 'Xhosa', nativeName: 'isiXhosa'),
    LanguageOption(code: 'af', englishName: 'Afrikaans', nativeName: 'Afrikaans'),
    LanguageOption(code: 'so', englishName: 'Somali', nativeName: 'Soomaali'),
    LanguageOption(code: 'rw', englishName: 'Kinyarwanda', nativeName: 'Ikinyarwanda'),
    LanguageOption(code: 'mg', englishName: 'Malagasy', nativeName: 'Malagasy'),
    LanguageOption(code: 'ne', englishName: 'Nepali', nativeName: 'नेपाली'),
    LanguageOption(code: 'si', englishName: 'Sinhala', nativeName: 'සිංහල'),
    LanguageOption(code: 'km', englishName: 'Khmer', nativeName: 'ខ្មែរ'),
    LanguageOption(code: 'lo', englishName: 'Lao', nativeName: 'ລາວ'),
    LanguageOption(code: 'id', englishName: 'Indonesian', nativeName: 'Bahasa Indonesia'),
    LanguageOption(code: 'ms', englishName: 'Malay', nativeName: 'Bahasa Melayu'),
    LanguageOption(code: 'tl', englishName: 'Filipino', nativeName: 'Filipino'),
    LanguageOption(code: 'ceb', englishName: 'Cebuano', nativeName: 'Binisaya'),
    LanguageOption(code: 'hu', englishName: 'Hungarian', nativeName: 'Magyar'),
    LanguageOption(code: 'cs', englishName: 'Czech', nativeName: 'Čeština'),
    LanguageOption(code: 'sk', englishName: 'Slovak', nativeName: 'Slovenčina'),
    LanguageOption(code: 'bg', englishName: 'Bulgarian', nativeName: 'Български'),
    LanguageOption(code: 'sr', englishName: 'Serbian', nativeName: 'Српски'),
    LanguageOption(code: 'hr', englishName: 'Croatian', nativeName: 'Hrvatski'),
    LanguageOption(code: 'sl', englishName: 'Slovenian', nativeName: 'Slovenščina'),
    LanguageOption(code: 'el', englishName: 'Greek', nativeName: 'Ελληνικά'),
    LanguageOption(code: 'he', englishName: 'Hebrew', nativeName: 'עברית'),
    LanguageOption(code: 'sv', englishName: 'Swedish', nativeName: 'Svenska'),
    LanguageOption(code: 'no', englishName: 'Norwegian', nativeName: 'Norsk'),
    LanguageOption(code: 'da', englishName: 'Danish', nativeName: 'Dansk'),
    LanguageOption(code: 'fi', englishName: 'Finnish', nativeName: 'Suomi'),
    LanguageOption(code: 'is', englishName: 'Icelandic', nativeName: 'Íslenska'),
    LanguageOption(code: 'ga', englishName: 'Irish', nativeName: 'Gaeilge'),
    LanguageOption(code: 'cy', englishName: 'Welsh', nativeName: 'Cymraeg'),
    LanguageOption(code: 'eu', englishName: 'Basque', nativeName: 'Euskara'),
    LanguageOption(code: 'ca', englishName: 'Catalan', nativeName: 'Català'),
    LanguageOption(code: 'gl', englishName: 'Galician', nativeName: 'Galego'),
    LanguageOption(code: 'lt', englishName: 'Lithuanian', nativeName: 'Lietuvių'),
    LanguageOption(code: 'lv', englishName: 'Latvian', nativeName: 'Latviešu'),
    LanguageOption(code: 'et', englishName: 'Estonian', nativeName: 'Eesti'),
    LanguageOption(code: 'mk', englishName: 'Macedonian', nativeName: 'Македонски'),
    LanguageOption(code: 'sq', englishName: 'Albanian', nativeName: 'Shqip'),
    LanguageOption(code: 'bs', englishName: 'Bosnian', nativeName: 'Bosanski'),
    LanguageOption(code: 'be', englishName: 'Belarusian', nativeName: 'Беларуская'),
    LanguageOption(code: 'ka', englishName: 'Georgian', nativeName: 'ქართული'),
    LanguageOption(code: 'hy', englishName: 'Armenian', nativeName: 'Հայերեն'),
    LanguageOption(code: 'az', englishName: 'Azerbaijani', nativeName: 'Azərbaycanca'),
    LanguageOption(code: 'kk', englishName: 'Kazakh', nativeName: 'Қазақша'),
    LanguageOption(code: 'ky', englishName: 'Kyrgyz', nativeName: 'Кыргызча'),
    LanguageOption(code: 'uz', englishName: 'Uzbek', nativeName: 'Oʻzbekcha'),
    LanguageOption(code: 'tg', englishName: 'Tajik', nativeName: 'Тоҷикӣ'),
    LanguageOption(code: 'tk', englishName: 'Turkmen', nativeName: 'Türkmençe'),
    LanguageOption(code: 'mn', englishName: 'Mongolian', nativeName: 'Монгол'),
    LanguageOption(code: 'bo', englishName: 'Tibetan', nativeName: 'བོད་སྐད'),
    LanguageOption(code: 'dz', englishName: 'Dzongkha', nativeName: 'རྫོང་ཁ'),
    LanguageOption(code: 'as', englishName: 'Assamese', nativeName: 'অসমীয়া'),
    LanguageOption(code: 'sd', englishName: 'Sindhi', nativeName: 'سنڌي'),
    LanguageOption(code: 'ks', englishName: 'Kashmiri', nativeName: 'कॉशुर'),
    LanguageOption(code: 'sa', englishName: 'Sanskrit', nativeName: 'संस्कृतम्'),
    LanguageOption(code: 'mai', englishName: 'Maithili', nativeName: 'मैथिली'),
    LanguageOption(code: 'bho', englishName: 'Bhojpuri', nativeName: 'भोजपुरी'),
    LanguageOption(code: 'doi', englishName: 'Dogri', nativeName: 'डोगरी'),
    LanguageOption(code: 'sat', englishName: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ'),
    LanguageOption(code: 'kok', englishName: 'Konkani', nativeName: 'कोंकणी'),
    LanguageOption(code: 'mni', englishName: 'Manipuri', nativeName: 'মৈতৈলোন্'),
    LanguageOption(code: 'brx', englishName: 'Bodo', nativeName: 'बड़ो'),
    LanguageOption(code: 'ug', englishName: 'Uyghur', nativeName: 'ئۇيغۇرچە'),
    LanguageOption(code: 'yi', englishName: 'Yiddish', nativeName: 'ייִדיש'),
    LanguageOption(code: 'lb', englishName: 'Luxembourgish', nativeName: 'Lëtzebuergesch'),
    LanguageOption(code: 'mt', englishName: 'Maltese', nativeName: 'Malti'),
    LanguageOption(code: 'fy', englishName: 'Frisian', nativeName: 'Frysk'),
    LanguageOption(code: 'gd', englishName: 'Scottish Gaelic', nativeName: 'Gàidhlig'),
    LanguageOption(code: 'br', englishName: 'Breton', nativeName: 'Brezhoneg'),
    LanguageOption(code: 'co', englishName: 'Corsican', nativeName: 'Corsu'),
    LanguageOption(code: 'haw', englishName: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi'),
    LanguageOption(code: 'mi', englishName: 'Maori', nativeName: 'Māori'),
    LanguageOption(code: 'sm', englishName: 'Samoan', nativeName: 'Gagana Samoa'),
    LanguageOption(code: 'to', englishName: 'Tongan', nativeName: 'Lea faka-Tonga'),
    LanguageOption(code: 'fj', englishName: 'Fijian', nativeName: 'Vosa Vakaviti'),
    LanguageOption(code: 'ay', englishName: 'Aymara', nativeName: 'Aymar aru'),
    LanguageOption(code: 'qu', englishName: 'Quechua', nativeName: 'Runa Simi'),
    LanguageOption(code: 'gn', englishName: 'Guarani', nativeName: 'Avañeʼẽ'),
    LanguageOption(code: 'ht', englishName: 'Haitian Creole', nativeName: 'Kreyòl ayisyen'),
    LanguageOption(code: 'ny', englishName: 'Chichewa', nativeName: 'Chichewa'),
    LanguageOption(code: 'sn', englishName: 'Shona', nativeName: 'chiShona'),
    LanguageOption(code: 'st', englishName: 'Sesotho', nativeName: 'Sesotho'),
    LanguageOption(code: 'tn', englishName: 'Tswana', nativeName: 'Setswana'),
    LanguageOption(code: 'ts', englishName: 'Tsonga', nativeName: 'Xitsonga'),
    LanguageOption(code: 've', englishName: 'Venda', nativeName: 'Tshivenḓa'),
    LanguageOption(code: 'lg', englishName: 'Luganda', nativeName: 'Luganda'),
    LanguageOption(code: 'ak', englishName: 'Akan', nativeName: 'Akan'),
    LanguageOption(code: 'ff', englishName: 'Fulah', nativeName: 'Fulfulde'),
    LanguageOption(code: 'wo', englishName: 'Wolof', nativeName: 'Wolof'),
    LanguageOption(code: 'bm', englishName: 'Bambara', nativeName: 'Bamanankan'),
    LanguageOption(code: 'ee', englishName: 'Ewe', nativeName: 'Eʋegbe'),
    LanguageOption(code: 'ti', englishName: 'Tigrinya', nativeName: 'ትግርኛ'),
    LanguageOption(code: 'om', englishName: 'Oromo', nativeName: 'Oromoo'),
    LanguageOption(code: 'ku', englishName: 'Kurdish', nativeName: 'Kurdî'),
    LanguageOption(code: 'ckb', englishName: 'Sorani Kurdish', nativeName: 'کوردیی ناوەندی'),
    LanguageOption(code: 'bal', englishName: 'Balochi', nativeName: 'بلۏچی'),
    LanguageOption(code: 'rn', englishName: 'Kirundi', nativeName: 'Ikirundi'),
    LanguageOption(code: 'kg', englishName: 'Kongo', nativeName: 'Kikongo'),
    LanguageOption(code: 'ln', englishName: 'Lingala', nativeName: 'Lingála'),
    LanguageOption(code: 'su', englishName: 'Sundanese', nativeName: 'Basa Sunda'),
    LanguageOption(code: 'mad', englishName: 'Madurese', nativeName: 'Basa Madhura'),
    LanguageOption(code: 'min', englishName: 'Minangkabau', nativeName: 'Baso Minangkabau'),
    LanguageOption(code: 'ace', englishName: 'Acehnese', nativeName: 'Bahsa Acèh'),
    LanguageOption(code: 'ban', englishName: 'Balinese', nativeName: 'Basa Bali'),
    LanguageOption(code: 'ilo', englishName: 'Ilocano', nativeName: 'Ilokano'),
    LanguageOption(code: 'war', englishName: 'Waray', nativeName: 'Winaray'),
    LanguageOption(code: 'pam', englishName: 'Kapampangan', nativeName: 'Kapampangan'),
    LanguageOption(code: 'hil', englishName: 'Hiligaynon', nativeName: 'Ilonggo'),
    LanguageOption(code: 'bcl', englishName: 'Bikol', nativeName: 'Bikol Central'),
  ];

  static LanguageOption findByCode(String code) {
    return all.firstWhere(
      (l) => l.code == code,
      orElse: () => all.first,
    );
  }
}
